# Generated by Django 5.1.2 on 2024-11-03 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUP',
            fields=[
                ('subAdminID', models.AutoField(primary_key=True, serialize=False)),
                ('subAdminName', models.CharField(max_length=255)),
                ('subAdminType', models.CharField(max_length=50)),
                ('subAdminEmail', models.EmailField(max_length=254, unique=True)),
                ('subAdminPhone', models.CharField(max_length=15)),
                ('subAdminCity', models.CharField(max_length=100)),
                ('subAdminState', models.CharField(max_length=100)),
                ('subAdminPinCode', models.CharField(max_length=10)),
                ('subAdminPassword', models.CharField(max_length=255)),
                ('subAdminReferralEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('subAdminLogo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('isActive', models.BooleanField(default=True)),
                ('subAdminRegisterDate', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('hasChosenPlan', models.BooleanField(default=False)),
                ('isFirstLogin', models.BooleanField(default=True)),
                ('hasUsedFreePlan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('planID', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=100)),
                ('planDescription', models.TextField()),
                ('planMonthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planAnnualPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DSCInPlan', models.CharField(default='', max_length=100)),
                ('planDuration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superAdminID', models.AutoField(primary_key=True, serialize=False)),
                ('superAdminUserID', models.CharField(max_length=255, unique=True)),
                ('superAdminPassword', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedbackText', models.TextField()),
                ('feedbackDate', models.DateTimeField(auto_now=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
        migrations.CreateModel(
            name='SubAdminSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('razorpayOrderID', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpayPaymentID', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpaySignature', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=100)),
                ('paymentID', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedGroup',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=255)),
                ('groupModifiedDate', models.DateTimeField(auto_now=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedCompany',
            fields=[
                ('companyID', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('companyModifiedDate', models.DateTimeField(auto_now=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userPhone', models.CharField(max_length=15)),
                ('userUsername', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('deactivatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('userModifiedDate', models.DateTimeField(auto_now=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
        migrations.AddField(
            model_name='updatedgroup',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser'),
        ),
        migrations.CreateModel(
            name='UpdatedDSC',
            fields=[
                ('dscID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=255)),
                ('receivedBy', models.CharField(default='', max_length=255)),
                ('receivedFrom', models.CharField(default='', max_length=255)),
                ('deliveredTo', models.CharField(default='', max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('renewalDate', models.DateTimeField(blank=True, null=True)),
                ('clientPhone', models.CharField(max_length=15)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedcompany')),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.AddField(
            model_name='updatedcompany',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser'),
        ),
        migrations.CreateModel(
            name='UpdatedClient',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=255)),
                ('clientPhone', models.CharField(max_length=15)),
                ('clientModifiedDate', models.DateTimeField(auto_now=True)),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedcompany')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('userPhone', models.CharField(max_length=15)),
                ('userUsername', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('deactivatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('userModifiedDate', models.DateTimeField()),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=255)),
                ('groupModifiedDate', models.DateTimeField()),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedgroup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryDSC',
            fields=[
                ('historyDSCID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=255)),
                ('receivedBy', models.CharField(default='', max_length=255)),
                ('receivedFrom', models.CharField(default='', max_length=255)),
                ('deliveredTo', models.CharField(default='', max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('renewalDate', models.DateTimeField(blank=True, null=True)),
                ('clientPhone', models.CharField(max_length=15)),
                ('modifiedDate', models.DateTimeField()),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedcompany')),
                ('dscID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateddsc')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyModifiedDate', models.DateTimeField()),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedcompany')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedgroup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('clientPhone', models.CharField(max_length=15)),
                ('clientModifiedDate', models.DateTimeField()),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedclient')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedcompany')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
            ],
        ),
    ]
