# Generated by Django 5.1.2 on 2024-11-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='last_login',
        ),
        migrations.AddField(
            model_name='signup',
            name='isIsActive',
            field=models.BooleanField(default=True),
        ),
    ]
