# Generated by Django 5.2 on 2025-05-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyuser',
            name='canReadOnly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historyuser',
            name='canReadWrite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historyuser',
            name='groupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.updatedgroup'),
        ),
        migrations.AddField(
            model_name='historyuser',
            name='isClientUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='freeUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updateduser',
            name='canReadOnly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='updateduser',
            name='canReadWrite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updateduser',
            name='groupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.updatedgroup'),
        ),
        migrations.AddField(
            model_name='updateduser',
            name='isClientUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historyannualfiling',
            name='modifiedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historypendingwork',
            name='modifiedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historywork',
            name='modifiedDate',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('trademarkID', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfTrademark', models.CharField(max_length=255)),
                ('applicationNo', models.CharField(default='', max_length=100)),
                ('classNo', models.CharField(default='', max_length=100)),
                ('nameOfApplicant', models.CharField(max_length=255)),
                ('dateOfApp', models.DateField()),
                ('status1', models.CharField(default='', max_length=50)),
                ('status2', models.CharField(default='', max_length=50)),
                ('hearingDate', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(default='', max_length=100)),
                ('oppDate', models.DateField(blank=True, null=True)),
                ('lastDate', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('indexSRN', models.IntegerField(blank=True, null=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedgroup')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTrademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTrademark', models.CharField(max_length=255)),
                ('applicationNo', models.CharField(default='', max_length=100)),
                ('classNo', models.CharField(default='', max_length=100)),
                ('nameOfApplicant', models.CharField(max_length=255)),
                ('dateOfApp', models.DateField()),
                ('status1', models.CharField(default='', max_length=50)),
                ('status2', models.CharField(default='', max_length=50)),
                ('hearingDate', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(default='', max_length=100)),
                ('oppDate', models.DateField(blank=True, null=True)),
                ('lastDate', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('modifiedDate', models.DateTimeField()),
                ('indexSRN', models.IntegerField(blank=True, null=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updatedgroup')),
                ('modifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.updateduser')),
                ('subAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
                ('trademarkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trademark')),
            ],
        ),
    ]
