# Generated by Django 5.1.2 on 2024-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_signup_last_login_signup_isisactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydsc',
            name='deliveredBy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='updateddsc',
            name='deliveredBy',
            field=models.CharField(default='', max_length=255),
        ),
    ]
