# Generated by Django 5.2 on 2025-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historyuser_canreadonly_historyuser_canreadwrite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyuser',
            name='canReadOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updateduser',
            name='canReadOnly',
            field=models.BooleanField(default=False),
        ),
    ]
